### ISSUE TITLE
Customer themed repo

### ISSUE THREAD

**Issue by Ztawh** [paxportse/style#1]
# Tasks
- [ ] Create British Airways repo
- [ ] Find and set theming
- [ ] Set up new page in Cloudflare

Create repo for every customer (ex: paxshop-ba, for British Airways)
Include the HTML-file and adjust theming to British Airways. Either look up colors and so on on their webpage or get it from Matilda.
Set up new page in Cloudflare  (https://ba.shop.paxport.group). Google how to or ask Simon.
